name: Deploy Sanity action

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint -- --max-warnings 0
    
      - name: Deploy Sanity Studio
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          npm install -g @sanity/cli
          sanity login --token $SANITY_AUTH_TOKEN
          sanity deploy --non-interactive
